build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 100
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInClasses: 25

style:
  MagicNumber:
    active: false
  ForbiddenComment:
    active: false

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
